import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Terms & Conditions | Zyberly Solutions",
  description: "Terms governing use of the Zyberly Solutions website and engagement of our digital services.",
};

const sections = [
  { title: "Acceptance and scope", content: <p>These terms govern your use of the Zyberly website and form the general framework for services supplied by Zyberly Solutions. By using the website, submitting an enquiry or engaging us, you agree to these terms. A signed proposal, statement of work or written agreement may add to or replace parts of these terms for a specific project.</p> },
  { title: "Our services", content: <><p>We provide digital strategy, branding, UI/UX design, website and application development, digital marketing, hosting, photography and related services. The exact scope, deliverables, timeline, revision allowance, dependencies and fees will be defined in the applicable proposal or agreement.</p><p>An enquiry or discussion does not guarantee availability, acceptance of a project or a particular result.</p></> },
  { title: "Client responsibilities", content: <><p>You agree to provide accurate instructions, timely feedback, authorised content, required access and a decision-maker able to approve work. You are responsible for ensuring that materials supplied to us—including text, images, trademarks, customer data and software—may lawfully be used for the project.</p><p>Delays in content, access, approvals or payment may reasonably move delivery dates.</p></> },
  { title: "Fees, invoices and changes", content: <><p>Fees, taxes, deposits, milestones and payment dates will be stated in the proposal or invoice. Unless agreed otherwise, deposits secure production time and work may pause while an invoice is overdue.</p><p>Requests outside the agreed scope may require a revised estimate, additional fee or timeline. Third-party costs such as domains, hosting, paid media, licences, stock assets and subscriptions are charged as agreed.</p></> },
  { title: "Intellectual property", content: <><p>Each party keeps ownership of materials, tools, know-how and intellectual property created or owned before the project. After full payment, the client receives the rights to final approved deliverables stated in the project agreement. Drafts, rejected concepts, internal methods, reusable components and third-party materials remain subject to their existing ownership or licence terms.</p><p>Zyberly may display completed public work in its portfolio and credentials unless the project agreement or a written confidentiality commitment says otherwise.</p></> },
  { title: "Third-party services", content: <p>Projects may rely on independent platforms such as domain registrars, hosting providers, payment gateways, content systems, analytics, advertising networks, app stores or external APIs. Their availability, pricing, policies and performance are outside our direct control. Their own terms govern their services.</p> },
  { title: "Review, launch and support", content: <><p>You are responsible for reviewing deliverables and identifying material issues during the agreed review period. Launch or publication indicates approval except for defects covered by a written warranty or support plan.</p><p>Maintenance, updates, security monitoring, content changes and ongoing support are included only when stated in the project scope or a separate support arrangement.</p></> },
  { title: "Confidentiality and data", content: <p>Each party will use reasonable care with confidential information received for the project and use it only for the engagement, except where disclosure is authorised or legally required. Personal information submitted through this website is handled as described in our <a href="/privacy-policy">Privacy Policy</a>.</p> },
  { title: "Warranties and liability", content: <><p>We will perform agreed services with reasonable professional care. Except for commitments expressly written in a project agreement, the website and services are provided without implied guarantees of uninterrupted operation, specific rankings, revenue, audience growth or compatibility with every future platform change.</p><p>To the extent permitted by law, neither party is liable for indirect, special or consequential loss. Zyberly’s aggregate liability relating to a project will not exceed the fees paid for the affected services, except where liability cannot lawfully be limited.</p></> },
  { title: "Suspension and termination", content: <p>Either party may end an engagement as allowed by its proposal or agreement. We may suspend work for overdue payment, unlawful requests, misuse, security risk or a material breach that is not remedied after reasonable notice. The client remains responsible for approved work completed and committed third-party costs up to termination.</p> },
  { title: "Law, disputes and contact", content: <><p>These terms are governed by the laws of India. The parties will first try in good faith to resolve concerns through direct discussion. Subject to applicable law and any written dispute clause, courts in Mumbai, Maharashtra will have jurisdiction.</p><p>Questions may be sent to <a href="mailto:info@zyberly.in">info@zyberly.in</a>.</p></> },
];

export default function TermsPage() {
  return <LegalDocument eyebrow="TERMS & CONDITIONS" title="CLEAR TERMS. BETTER WORK." intro="The practical rules for using our website and building digital products with Zyberly." updated="26 JULY 2026" sections={sections} />;
}
