import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy | Zyberly Solutions",
  description: "How Zyberly Solutions collects, uses, protects and manages personal information.",
};

const sections = [
  { title: "Who we are", content: <><p>Zyberly Solutions is a Mumbai-based digital studio providing strategy, branding, design, development, marketing, hosting and related creative services. In this policy, “Zyberly”, “we”, “our” and “us” refer to Zyberly Solutions.</p><p>This policy applies to information collected through this website, project enquiries and direct business communications.</p></> },
  { title: "Information we collect", content: <><p>When you submit an enquiry, we may collect your name, work email, phone number, company, selected service and project details. If we work together, we may also receive billing details, brand assets, project files, account access supplied by you and communications required to deliver the engagement.</p><p>Our hosting infrastructure may automatically record limited technical data such as IP address, browser type, device information, requested pages, timestamps and security logs.</p></> },
  { title: "How we use information", content: <><p>We use information to respond to enquiries, prepare proposals, communicate about projects, deliver and support services, process payments, maintain security, improve our website, meet record-keeping duties and protect our legal rights.</p><p>We do not sell personal information or use enquiry details for unrelated advertising without an appropriate choice or permission.</p></> },
  { title: "Legal basis and consent", content: <p>We process information for lawful business purposes, including responding to your request, taking steps toward or performing a contract, meeting legal obligations and operating a secure service. Where consent is the appropriate basis, you may withdraw it by contacting us; withdrawal does not affect processing already completed lawfully.</p> },
  { title: "Service providers and sharing", content: <><p>We may share only the information reasonably necessary with trusted providers supporting email delivery, cloud hosting, analytics, payment processing, development, communications or professional advice. They may process information only for the relevant service and subject to their own contractual and legal duties.</p><p>We may disclose information when required by law, to respond to lawful authority, prevent fraud or security threats, or during a genuine business reorganisation. We do not rent or trade contact-form submissions.</p></> },
  { title: "Cookies and external services", content: <p>The website may use essential storage needed for security and functionality. Embedded or linked services—such as Google Maps, WhatsApp, portfolio websites or social platforms—may process information under their own privacy terms when you interact with them. You can control non-essential cookies through your browser where applicable.</p> },
  { title: "Retention and security", content: <><p>We retain enquiry records only as long as reasonably needed for follow-up, business records, dispute prevention and legal compliance. Client project and financial records may be retained for the period required by contract, tax or applicable law.</p><p>We use reasonable administrative and technical safeguards, including restricted access and protected service credentials. No internet system can be guaranteed completely secure, so please avoid sending unnecessary sensitive information through the enquiry form.</p></> },
  { title: "Your choices and rights", content: <><p>Subject to applicable law, you may ask us to confirm whether we hold your personal information, request access or correction, ask for deletion where retention is no longer required, withdraw consent, or raise a grievance about our handling of your data.</p><p>Send requests to <a href="mailto:info@zyberly.in">info@zyberly.in</a>. We may need to verify your identity before acting on a request.</p></> },
  { title: "International processing and children", content: <><p>Some technology providers may process data outside your state or country. Where this occurs, we take reasonable steps to use reputable providers and protections appropriate to the service.</p><p>Our services are intended for businesses and adults. We do not knowingly request personal information from children. A parent or guardian who believes a child has submitted information should contact us for removal.</p></> },
  { title: "Updates and contact", content: <><p>We may update this policy when our services, technology or legal responsibilities change. The latest version will be published here with a revised date.</p><p>Privacy enquiries: <a href="mailto:info@zyberly.in">info@zyberly.in</a><br />Zyberly Solutions, Shop No. 3, Nepean Sea Road, Malabar Hill, Mumbai, Maharashtra 400026, India.</p></> },
];

export default function PrivacyPolicyPage() {
  return <LegalDocument eyebrow="PRIVACY POLICY" title="YOUR DATA. HANDLED WITH CARE." intro="A clear explanation of what we collect, why we use it and the choices available to you." updated="26 JULY 2026" sections={sections} />;
}
